indices = """
title
10 top time-saving tech tips                                                  0
Who am I? Think again                                                         1
"Awoo"                                                                        2
What I learned from 2,000 obituaries                                          3
Why giving away our wealth has been the most satisfying thing we've done      4
How to save the world (or at least yourself) from bad meetings                5
Photos that changed the world                                                 6
For parents, happiness is a very high bar                                     7
Cradle to cradle design                                                       8
To create for the ages, let's combine art and engineering                     9
Art made of storms                                                           10
How I'm fighting bias in algorithms                                          11
There's no shame in taking care of your mental health                        12
Singing the primal mystery                                                   13
Fighters and mourners of the Ukrainian revolution                            14
What really motivates people to be honest in business                        15
3 ways to spot a bad statistic                                               16
Why stay in Chernobyl? Because it's home.                                    17
How the blockchain will radically transform the economy                      18
The hidden influence of social networks                                      19
How your brain tells you where you are                                       20
How to get better at the things you care about                               21
A new equation for intelligence                                              22
The hunt for General Tso                                                     23
How the Internet enables intimacy                                            24
How data from a crisis text line is saving lives                             25
Happiness in body and soul                                                   26
A dance in a hurricane of paper, wind and light                              27
A vision for sustainable restaurants                                         28
Visualizing the wonder of a living cell                                      29
"""

transcripts = """
0      I've noticed something interesting about socie...
1      Hetain Patel: (In Chinese)Yuyu Rau: Hi, I'm He...
2      (Music)Sophie Hawley-Weld: OK, you don't have ...
3      Joseph Keller used to jog around the Stanford ...
4      Chris Anderson: So, this is an interview with ...
5      Picture this: It's Monday morning, you're at t...
6      In my industry, we believe that images can cha...
7      When I was born, there was really only one boo...
8      In 1962, with Rachel Carson's "Silent Spring,"...
9      Good morning. When I was a little boy, I had a...
10     (Music)What you just heard are the interaction...
11     Hello, I'm Joy, a poet of code, on a mission t...
12     Last year ... was hell.(Laughter)It was my fir...
13     (Singing)(Singing ends)(Applause)Pep Rosenfeld...
14     When I arrived in Kiev, on February 1 this yea...
15     How many companies have you interacted with to...
16     I'm going to be talking about statistics today...
17     Three years ago, I was standing about a hundre...
18     Economists have been exploring people's behavi...
19     For me, this story begins about 15 years ago, ...
20     When we park in a big parking lot, how do we r...
21     Most of us go through life trying to do our be...
22     Intelligence — what is it? If we take a look b...
23     There are more Chinese restaurants in this cou...
24     I believe that there are new, hidden tensions ...
25     A girl I've never met before changed my life a...
26     I bet you're worried.(Laughter)I was worried. ...
27                                     (Music)(Applause)
28     Restaurants and the food industry in general a...
29     I'm a medical illustrator, and I come from a s...
"""

# Initialize the TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')

# Construct the TF-IDF matrix
tfidf_matrix = tfidf.fit_transform(transcripts)

# Generate the cosine similarity matrix
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

# Generate recommendations
print(get_recommendations('5 ways to kill your dreams', cosine_sim, indices))